---
- hosts: prod
  become: True
  tasks:
    - name: Install python3
      apt:
        name: python3
        state: present
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
    - name: Install docker
      apt:
        name: docker-compose
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: javahometech
        image: "rajeshdevopsengineer24/tomcatjava:3.0"
        state: started
        published_ports:
          - 0.0.0.0:8000:8080
