import "@/styles/globals.css";

import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import type { PropsWithChildren } from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ApolloProvider from "@/providers/apollo";

const primary = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={`${primary.variable} antialiased`}>
        <ApolloProvider>
          <div className="min-h-screen bg-gray-50">
            <Header />
            {children}
            <Footer />
          </div>
        </ApolloProvider>
      </body>
    </html>
  );
}
